export const engUnits = {
  bag: ['bag', 'bags'],
  box: ['box'],
  can: ['can'],
  cup: ['cup','c', 'c.', 'C', 'Cups'],
  clove: ['clove'],
  gallon: ['gallon','gal'],
  ounce: ['ounce','oz', 'oz.'],
  pint: ['pint','pt', 'pts', 'pt.'],
  pound: ['pound','lb', 'lb.', 'lbs', 'lbs.', 'Lb', 'Lbs'],
  quart: ['quart','qt', 'qt.', 'qts', 'qts.'],
  tablespoon: ['tbs', 'tbsp', 'tbspn', 'T', 'T.', 'Tablespoons', 'Tablespoon'],
  teaspoon: ['teaspoon','tsp', 'tspn', 't', 't.'],
  gram: ['gram','g', 'g.'],
  kilogram: ['kilogram','kg', 'kg.', 'Kg', 'Kg.'],
  liter: ['liter','l', 'l.', 'lt', 'Lt', 'LT', 'L', 'L.'],
  milligram: ['milligram','mg', 'mg.'],
  milliliter: ['milliliter','ml', 'ml.', 'mL', 'mL.'],
  package: ['package','pkg', 'pkgs'],
  stick: ['stick','sticks'],
  piece: ['piece','pcs', 'pcs.'],
  pinch: ['pinch'],
  small: ['Small'],
  slice: ['slice'],
  medium: ['Medium'],
  large: ['large', 'Large'],
} as { [key: string]: string[] };

export const engPluralUnits = {
  cup: 'cups',
  gallon: 'gallons',
  ounce: 'ounces',
  pint: 'pints',
  pound: 'pounds',
  quart: 'quarts',
  tablespoon: 'tablespoons',
  teaspoon: 'teaspoons',
  gram: 'grams',
  kilogram: 'kilograms',
  liter: 'liters',
  milligram: 'milligrams',
  milliliter: 'milliliters',
  clove: 'cloves',
  bag: 'bags',
  box: 'boxes',
  pinch: 'pinches',
  can: 'cans',
  slice: 'slices',
  piece: 'pieces'
} as { [key: string]: string };

export const engNameToSymbol= {
  cup: 'c',
  gallon: 'gal',
  ounce: 'oz',
  pint: 'pt',
  pound: 'lb',
  quart: 'qt',
  tablespoon: 'tbs',
  teaspoon: 'tsp',
  gram: 'g',
  kilogram: 'kg',
  liter: 'lt',
  milligram: 'mg',
  milliliter: 'ml',
  clove: '',
  bag: '',
  box: '',
  pinch: '',
  can: '',
  slice: '',
  piece: ''
} as { [key: string]: string };

export const engPreposition = ['of'];


export const itaUnits = {
  bicchiere: ['bicchiere'],
  bustina: ['bustina', 'bustine'],
  cucchiaio: ['cucchiai','cucchiaio'],
  cucchiaino: ['cucchiaini','cucchiaino'],
  grammo: ['g', 'g.', 'gr', 'gr.','grammi','grammo'],
  chilogrammo: ['kg', 'kg.', 'KG','Kg', 'Kg.', 'kilogrammo', 'chilogrammi','kilogrammo','chilogrammo'],
  fetta: ['fetta', 'fette'],
  foglia: ['foglie','foglia'],
  litro: ['l', 'l.', 'L', 'L.', 'lt','Litro','litro'],
  mazzetto: ['Mazzetto','mazzetti','mazzetto'],
  lattina: ['Lattina','lattina'],
  milligrammo: ['mg', 'mg.', 'milligrammo','milligrammo'],
  millilitro: ['ml', 'ml.', 'mL', 'mL.', 'millilitro'],
  panetto: ['Panetto', 'panetti', 'panetto'],
  pacco: ['pkg', 'pkgs', 'pacchetto','pacco'],
  pezzo: ['pezzo','pcs', 'pcs.','pezzi'],
  pizzico: ['pizzico','pizzichi'],
  tazza: ['tazza', 'tazzina','tazzine'],
  spicchio: ['spicchio', 'spicchi'],
  scatola: ['scatola', 'scatole'],
  vasetto: ['vasetto', 'vasetti'],
} as { [key: string]: string[] };

export const itaPluralUnits = {
  bicchiere: 'bicchieri',
  bustina: 'bustine',
  tazza: 'tazze',
  quarto: 'quarti',
  cucchiaio: 'cucchiai',
  cucchiaino: 'cucchiaini',
  grammo: 'grammi',
  chilogrammo: 'chilogrammi',
  litro: 'litri',
  milligrammo: 'milligrammi',
  millilitro: 'millilitri',
  spicchio: 'spicchi',
  scatola: 'scatole',
  pizzico: 'pizzichi',
  lattina: 'lattine',
  fetta: 'fette',
  pezzo: 'pezzi',
  panetto: 'panetti',
  foglia: 'foglie',
  mazzetto: 'mazzetti',
  vasetto: 'vasetti'
} as { [key: string]: string };

export const itaNameToSymbol = {
  bicchiere: '',
  bustina: '',
  tazza: '',
  quarto: '',
  cucchiaio: '',
  spicchio: '',
  scatola: '',
  pizzico: '',
  lattina: '',
  fetta: '',
  pezzo: '',
  panetto: '',
  foglia: '',
  mazzetto: '',
  vasetto: '',
  grammo: 'g',
  cucchiaino: 'cc',
  chilogrammo: 'kg',
  litro: 'lt',
  milligrammo: 'mg',
  millilitro: 'ml',
} as { [key: string]: string };

export const itaPreposition = ['di','d\''];

export const  unitsMap = new Map();
unitsMap.set("eng",[engUnits,  engPluralUnits, engPreposition, engNameToSymbol]);
unitsMap.set("ita",[itaUnits,  itaPluralUnits, itaPreposition, itaNameToSymbol]);

